### ISSUE TITLE
cunumeric.linspace(0,2,5) failed

### ISSUE THREAD

**Issue by z778520016** [nv-legate/cunumeric#975] opened 2023-06-26 13:22 UTC
I build cunumeric from conda using the command as follows:
`conda install -c nvidia -c conda-forge -c legate legate-core`
`conda install cunumeric -c nvidia -c conda-forge -c legate`
however,when I use linspace(0,2,5), error occurs:
both happens in python3.9 and python3.10
```WARNING: Disabling control replication for interactive run
Welcome to Legion Python interactive console
>>> import numpy
>>> numpy.linspace(0,2,5)
array([0. , 0.5, 1. , 1.5, 2. ])
>>> import cunumeric
...
  File "/xx/anaconda3/envs/cunumeric/lib/python3.9/site-packages/cunumeric/array.py", line 306, in __array_function__
    return cn_func(*args, **kwargs)
  File "/xxx/anaconda3/envs/cunumeric/lib/python3.9/site-packages/cunumeric/coverage.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/xxx/anaconda3/envs/cunumeric/lib/python3.9/site-packages/cunumeric/array.py", line 306, in __array_function__
    return cn_func(*args, **kwargs)
  File "/xxx/anaconda3/envs/cunumeric/lib/python3.9/site-packages/cunumeric/coverage.py", line 110, in wrapper
    return func(*args, **kwargs)
RecursionError: maximum recursion depth exceeded

**Comment by manopapad** [comment] 2023-06-26 17:12
I was not able to reproduce this. I built my conda env like so:

```
conda create -n bug975b -c nvidia -c conda-forge -c legate legate-core cunumeric python=3.9 cuda-version=11.8
```

(I had to explicitly specify `cuda-version` due to an unrelated issue, that has been fixed with https://github.com/nv-legate/legate.core/pull/753).

then I ran like so:

```
mpapadakis@prm-dgx-02:~$ legate
Welcome to Legion Python interactive console
>>> import numpy
>>> numpy.linspace(0,2,5)
array([0. , 0.5, 1. , 1.5, 2. ])
>>> import cunumeric
>>> cunumeric.linspace(0,2,5)
array([0. , 0.5, 1. , 1.5, 2. ])
>>>
```

What version of legate-core, cunumeric are you using? The line numbers you quoted seem to point to an version from 2022, whereas the latest version available on conda is 23.03.

Can you show how you're running `legate`, and from which directory?

Is there more relevant output in the `...` part of your output? I assume you're hitting this issue when you're trying to use `cunumeric.linspace`, but I don't see that on your output.

**Comment by z778520016** [comment] 2023-06-27 02:04
It`s due to the legate version.When I install legate as follows,the version is 22.08.00.
```
conda create -n cunumeric23 python=3.9

**Comment by manopapad** [comment] 2023-06-27 04:46
I see. What might be happening is that the initial environment creation command `conda create -n cunumeric23 python=3.9` is installing some package version that is constraining the versions of legate.core and cunumeric if they're added later.

If you have the bandwidth to help figure out what's happening here, then please try the following and see what error message it produces.

```
conda create -n test python=3.9
conda activate test
conda install -c nvidia -c conda-forge -c legate legate-core=23.03
```

Otherwise, it sounds like you're happy with the environment that's produced with the following command?

```
conda create -n bug975b -c nvidia -c conda-forge -c legate legate-core cunumeric python=3.9 cuda-version=11.8
```

**Comment by z778520016** [comment] 2023-06-27 13:49
No error message shows,the legate `23.03` can be installed,so maybe if I do not specify the newest version,an old version will be installed.

**Comment by manopapad** [comment] 2023-06-27 20:34
I see, so just to summarize, it sounds like
```
conda create -n test python=3.9
conda activate test
conda install -c nvidia -c conda-forge -c legate legate-core
```
works, but installs 22.08. If we additionally constrain the version of `legate-core`
```
conda create -n test python=3.9
conda activate test
conda install -c nvidia -c conda-forge -c legate legate-core=23.03
```
then that also works, and installs 23.03. Maybe this is some weirdness of the conda dependency resolution, pinging @m3vaz in case he knows.

In any case, @z778520016 does this command solve your immediate issue?

```
conda create -n ... -c nvidia -c conda-forge -c legate legate-core cunumeric python=3.9 cuda-version=11.8
```

In that case we can go ahead and close this issue.

**Comment by z778520016** [comment] 2023-06-28 01:09
Yes,it solves,thanks.

**Closed** 2023-06-28 01:09 UTC
