### ISSUE TITLE
`uninitialized data for field` error

### ISSUE THREAD

**Issue by marcinz** [nv-legate/cunumeric#32] opened 2021-05-24 23:56 UTC
It seems that one of the recent commits (possibly e24dbddbb6a0aad483a8a96c513b2d05fd70e073) introduced the following error for some codes:

```
[0 - 7f743c098700]   10.165263 {5}{runtime}: [error 68] LEGION ERROR: Region requirement 1 of operation legate::numpy::NoncommutativeBinaryUniversalFunction<legate::numpy::SubtractOperation<double> >::NormalTask (UID 164) in parent task legion_python_main (UID 1) is using uninitialized data for field(s) 1048579 of logical region (16,1,1) with read-only privileges (from file /gpfs/fs1/mzalewski/repos/quickstart-collection/legate.core/legion/runtime/legion/legion_ops.cc:1170)
```

**Comment by lightsighter** [comment] 2021-05-25 00:02
Why didn't that get caught by the CI? I don't think I received an email about it failing.

**Comment by lightsighter** [comment] 2021-05-25 00:03
Can you provide a command line to reproduce it? I feel like I should fix it since I broke it.

**Comment by marcinz** [comment] 2021-05-25 00:39
Honestly, I am not sure why it did not get caught. I think that the operations that trigger it are not a part of the test suite.

**Comment by lightsighter** [comment] 2021-05-25 03:23
This should be fixed with 026ab9afd3

**Comment by manopapad** [comment] 2021-07-28 19:19
@marcinz can you confirm that this has been fixed?

**Comment by magnatelee** [comment] 2022-05-11 03:07
this issue is obsolete, as the offending task in the original report no longer exists in the current codebase.

**Closed by magnatelee** 2022-05-11 03:07 UTC
Labels: bug, in progress
