### ISSUE TITLE
cunumeric does not issue unimplemented warnings for functions in submodules

### ISSUE THREAD

**Issue by rohany** [nv-legate/cunumeric#761] opened 2023-01-22 19:00 UTC
For example, calling unsupported functions in the `random` module silently fall back to numpy instead of issuing a warning.

**Comment by manopapad** [comment] 2023-01-23 23:12
Tentatively assigning to @bryevdv, who mostly recently touched the module-wrapping logic. Hopefully there's a simple extension we could make.

**Comment by bryevdv** [comment] 2023-01-23 23:15
Do we want to warn only on first use, or every call?

**Comment by bryevdv** [comment] 2023-01-23 23:16
Or for that matter, do we want to only warn on _any_ first use, with an actionable message about generating API coverage report output?

**Comment by manopapad** [comment] 2023-01-23 23:21
For modules where we have partial coverage, I like the current behavior of warning for each missing function separately, but only the first time it's called.

If we're talking about a whole module missing, then it would be nice to warn once, on the first use of any function in that module. But if that's too hard, then warning on the first use of each function from the module would still be OK IMHO.

Noting the possibility of API coverage reporting could be an option in all scenarios I assume.

**Comment by bryevdv** [comment] 2023-01-23 23:25
So, there already should be a warning emitted:

https://github.com/nv-legate/cunumeric/blob/35ebbb741838c34f0f0cb9d96ad0077cbb424d14/cunumeric/coverage.py#L178-L189

**Comment by bryevdv** [comment] 2023-01-23 23:26
@rohany can you provide a concrete minimal reproducer?

**Comment by bryevdv** [comment] 2023-01-23 23:33
Here is an example that does print a warning, for instance:
```
import cunumeric as np
A = np.diag([1.0, 2, 3])
print(np.flipud(A))
```
This yields:
```
dev310 ❯ legate foo.py                            
foo.py:3: RuntimeWarning: cuNumeric has not implemented numpy.flipud and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
  print(np.flipud(A))
```
Note that  currently warnings only emitted when coverage reporting is _not_ turned on. i.e. if you have added the command line option `cunumeric:report:coverage`, then there won't (currently) be any warning. Though this could be changed if desired.

**Comment by bryevdv** [comment] 2023-01-23 23:40
Also noting that the current behavior seems to be to de-dupe the warnings, at least at a given stack level.

**Comment by bryevdv** [comment] 2023-01-23 23:47
Noting the current behavior does not de-dupe so we could also certainly improve that, although the advantage of not de-duping is that the user gets line numbers:
```
dev310 ❯ legate foo.py                                                               
foo.py:3: RuntimeWarning: cuNumeric has not implemented numpy.flipud and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
  np.flipud(A)
foo.py:4: RuntimeWarning: cuNumeric has not implemented numpy.flipud and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
  np.flipud(A)
foo.py:5: RuntimeWarning: cuNumeric has not implemented numpy.flipud and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
  np.flipud(A)
foo.py:6: RuntimeWarning: cuNumeric has not implemented numpy.flipud and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
  np.flipud(A)
foo.py:7: RuntimeWarning: cuNumeric has not implemented numpy.flipud and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
  np.flipud(A)
```
so maybe it is better to keep as it is.

**Comment by rohany** [comment] 2023-01-23 23:50
Try calling `cunumeric.random.permutation`. This shouldn't issue a warning, but `permutation` is unimplemented by `cunumeric`.

**Comment by bryevdv** [comment] 2023-01-23 23:53
@rohany can you please provide an actual [complete, minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), so as to avoid any and all speculation and ambiguity?

Also can clarify this statement:

>  This shouldn't issue a warning, but permutation is unimplemented by cunumeric.

Did you mean it *should* issue a warning?

**Comment by rohany** [comment] 2023-01-23 23:55
```
Welcome to Legion Python interactive console
>>> import cunumeric
>>> cunumeric.random.permutation(5)
array([1, 4, 2, 3, 0])
```
> Did you mean it should issue a warning?

Sorry I was confusing. I meant that I expect a warning, but running that code is not going to raise a warning (unless something changed in the meantime).

**Comment by bryevdv** [comment] 2023-01-24 00:06
OK now we are getting somewhere.

@manopapad I think coverage just does not work with `np.random` in general. I don't think it was got considered when all the bitgenerator work went in. This will require some investigation. The coverage codepaths are already fairly convoluted and unpleasantly special-cased.

**Comment by bryevdv** [comment] 2023-01-24 00:19
Maybe that was too pessimistic. I think some things _are_ getting wrapped properly, e.g `np.random.normal` but not others, like `np.random.permutation`. The proximate cause for that is:
```
>>> isinstance(m.permutation, (FunctionType, MethodType, MethodDescriptorType))
False
```
Which I guess probably has something to do with this odd type not being covered by the above:
```
>>> type(m.permutation)
<class 'builtin_function_or_method'>
```

**Comment by bryevdv** [comment] 2023-01-24 00:21
This returns True, but I'll have to see if just adding this to `should_wrap` is a good idea or not:
```
>>> isinstance(m.permutation, types.BuiltinMethodType)
True
```

**Comment by bryevdv** [comment] 2023-01-24 00:27
Yes, well, this diff "fixes" 
```diff
diff --git a/cunumeric/coverage.py b/cunumeric/coverage.py
index f8f4446a..acf5ba01 100644
--- a/cunumeric/coverage.py
+++ b/cunumeric/coverage.py
@@ -17,7 +17,7 @@ from __future__ import annotations
 import warnings
 from dataclasses import dataclass
 from functools import wraps
-from types import FunctionType, MethodDescriptorType, MethodType, ModuleType
+from types import BuiltinMethodType, FunctionType, MethodDescriptorType, MethodType, ModuleType
 from typing import Any, Container, Mapping, Optional, cast
 
 import numpy as np
@@ -230,7 +230,7 @@ def clone_module(
         # Only need to wrap things that are in the origin module to begin with
         if attr not in origin_module.__dict__:
             continue
-        if isinstance(value, (FunctionType, lgufunc)):
+        if isinstance(value, (BuiltinMethodType, FunctionType, lgufunc)):
             wrapped = implemented(
                 cast(AnyCallable, value), mod_name, attr, reporting=reporting
             )
@@ -239,7 +239,7 @@ def clone_module(
     from numpy import ufunc as npufunc
 
     for attr, value in missing.items():
-        if isinstance(value, (FunctionType, npufunc)):
+        if isinstance(value, (BuiltinMethodType, FunctionType, npufunc)):
             wrapped = unimplemented(value, mod_name, attr, reporting=reporting)
             new_globals[attr] = wrapped
         else:
@@ -247,7 +247,7 @@ def clone_module(
 
 
 def should_wrap(obj: object) -> bool:
-    return isinstance(obj, (FunctionType, MethodType, MethodDescriptorType))
+    return isinstance(obj, (BuiltinMethodType, FunctionType, MethodType, MethodDescriptorType))
 
 
 def clone_np_ndarray(cls: type) -> type:
```
produces:
```
dev310 ❯ legate foo.py
foo.py:2: RuntimeWarning: cuNumeric has not implemented numpy.random.permutation and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
  np.random.permutation(5)
```

But unfortunately causes other things to explode: 
```
   TypeError: ndarray.__array__() missing 1 required positional argument: 'self'
   /home/bryan/work/legate.core/legate/core/context.py:277: RuntimeWarning: cuNumeric has not implemented numpy.ndarray.__new__ and is falling back to canonical numpy. You may notice significantly decreased performance for this function call.
     result = func(*args, **kwargs)
```

I guess I am really not sure why  `permutation` has the type `builtin_function_or_method` to begin with. That seems wrong, but is certainly a huge pain, regardless.

**Closed** 2023-01-24 22:28 UTC
